#cloud-config
users:
  - name: ${loginUser}
    groups: [sudo]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${public_key_robin}
      
ssh_keys:
  ed25519_private: |
    ${tls_private_key}
ssh_pwauth: false

package_update: true
package_upgrade: true
package_reboot_if_required: true

runcmd:
  - sudo mkdir -p /volume01
  - echo "`/bin/ls /dev/disk/by-id/*${volId}` /volume01 xfs discard,nofail,defaults 0 0" >> /etc/fstab
  - sudo systemctl daemon-reload
  - sudo mount -a
