#cloud-config
users:
  - name: ${loginUser}
    groups: [sudo]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${public_key_robin}
      
ssh_keys:
  ed25519_private: |
    ${tls_private_key}
ssh_pwauth: false

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - fail2ban
  - plocate
  - python3-systemd # Add python3-systemd for fail2ban backend

write_files:
  path: /etc/fail2ban/jail.local
  content: |
    [DEFAULT]
    # Ban hosts for 1 hour:
    bantime = 1h

    # Override /etc/fail2ban/jail.d/defaults-debian.conf:
    backend = systemd

    [sshd]
    enabled = true
    # To use internal sshd filter variants

runcmd:
  - sudo mkdir -p /volume01
  - echo "`/bin/ls /dev/disk/by-id/*${volId}` /volume01 xfs discard,nofail,defaults 0 0" | sudo tee -a /etc/fstab
  - sudo systemctl daemon-reload
  - sudo mount -a
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - updatedb
  - systemctl restart fail2ban
